config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  get '/about', to: 'public/homes#about', as: 'about'
  # 退会処理
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe', as: 'public_customers_unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  get '/admin', to: 'admin/homes#top', as: 'admin_root'
  get 'customers/my_page', to: 'public/customers#show', as: 'public_customers'
  get 'customers/information/edit', to: 'public/customers#edit', as: 'public_customers_information_edit'

  get 'addresses', to: 'public/addresses#index', as: 'addresses'
  get 'addresses/:id/edit', to: 'public/addresses#edit', as: 'addresses_edit'
  patch 'public/addresses/:id', to: 'public/addresses#update'


  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  post '/customers/sign_in', to: 'public/sessions#create'

  namespace :public, path: '' do
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create] do
        post 'confirm', on: :collection
        get 'thanks', on: :collection
    end
    resources :items, except: [:destroy]
    resources :cart_items, only: [ :update, :destroy, :create, :show] do
      delete :destroy_all, on: :collection
    end
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
    # 修正した部分
    delete 'cart_items', to: 'cart_items#destroy_all'
    get 'cart_items', to: 'cart_items#index'  # カートアイテムを表示するためのルートを追加
  end
  # Move public/cart_items route definition outside of public namespace

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :homes, only: [:top]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, optional: true
  has_many :cart_items

  validates :genre, presence: { message: "を選択してください" }
  validates :price, presence: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validates :introduction, presence: true, length: { maximum: 70 }

  scope :search, ->(query) {
    where("name LIKE ?", "%#{query}%") if query.present?
  }

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!
  def index
   @items = Item.search(params[:q]).page(params[:page])
  end

  def new
   @item = Item.new
   @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
     flash[:notice] = "商品を追加しました。"
      redirect_to admin_item_path(@item.id)
    else
     flash.now[:alert] = "商品の追加に失敗しました。"
      render new_admin_item_path
    end
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
   @genres = Genre.all
  end

 def update
   @item = Item.find(params[:id])
   @genres = Genre.all
   if @item.update(item_params)
    flash[:notice] = "状態を変更しました。"
     redirect_to admin_item_path(@item.id)
   else
     flash.now[:alert] = "状態の変更に失敗しました。"
     render :edit
   end
 end

    private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<div class='container' style="margin-top: 100px; margin-bottom: 100px;">
  <div class='row'>
    <div class="col-sm-10 col-md-8 col-lg-6 px-5 px-sm-0 mx-auto">
      <h3 class="text-center"><%= title %></h3>
      <% if @item.errors.any? %>
        <div class="alert alert-danger">
          <%= @item.errors.count %>件のエラーが発生しました
          <ul class="mb-0">
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message.gsub("Genre", "ジャンル").gsub("Price", "価格").gsub("Name", "商品名").gsub("Image", "商品画像").gsub("Introduction", "商品説明") %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with url: url, method: method, model: item do |f| %>
      <table class="table table-borderless">
        <tr>
          <th class="text-end">商品画像</th>
            <td>
              <%= f.file_field :image, accept: "image/*", class: "btn btn-outline-secondary " %>
            </td>
        </tr>
        <tr>
          <th class="text-end">商品名</th>
          <td><%= f.text_field :name, class: 'form-control' %></td>
        </tr>
        <tr>
          <th class="text-end">商品説明</th>
          <td><%= f.text_area :introduction, class: 'form-control' %></td>
        </tr>
        <tr>
          <th class="text-end">税抜価格</th>
          <td><%= f.text_field :price, class: 'form-control', pattern: "[0-9]+", placeholder: '半角' %></td>
        </tr>
        <tr>
          <th class="text-end">ジャンル</th>
          <td>
            <div class="form-group">
              <%= f.select :genre_id, options_for_select((@genres || []).map { |genre| [genre.name, genre.id] }, item.genre_id), { prompt: "選択してください" }, class: 'form-control' %>
            </div>
          </td>
        </tr>
        <tr>
          <th class="text-end">販売ステータス</th>
          <td>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <label class="btn btn-outline-success <%= 'active' if item.is_active %> rounded">
                <%= f.radio_button :is_active, true, { checked: item.is_active, class: 'form-check-input', id: 'active' } %> 販売中
              </label>
              <div class="mx-2"></div> <!-- ボタン間のスペースを調整するための空のディビジョン -->
              <label class="btn btn-outline-danger <%= 'active' unless item.is_active %> rounded">
                <%= f.radio_button :is_active, false, { checked: !item.is_active, class: 'form-check-input', id: 'inactive' } %> 販売停止中
              </label>
            </div>
          </td>
        </tr>
      </table>
      <div class="text-center">
        <%= f.submit submit_button_text, class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<%= render partial: 'admin/items/form', locals: { title: '商品編集', url: admin_item_path(@item), method: :patch, item: @item, genres: @genres, submit_button_text: '変更を保存' } %>

app/views/admin/items/index.html.erb
<!--管理者側の商品一覧ページ-->
<div class="col-sm-9 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto align-self-center text-start" style="margin-top: 50px; margin-bottom: 50px;">
  <div class="d-flex justify-content-around">
    <h3>商品一覧</h3>
    <%= link_to '新規登録', new_admin_item_path, class: "btn btn-outline-secondary" %>
    </div>
    <div style="margin-top: 5px; margin-bottom: 5px;"></div>
    <div>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do|item| %>
          <tr>
            <td>
            <%= item.id %>
            </td>
            <td>
              <%= link_to admin_item_path(item) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td>
            <%= number_with_delimiter(item.price) %>
            </td>
            <td>
            <%= item.genre.name %>
            </td>
            <td>
            <% if item.is_active %>
            <span class='text-success'>販売中</span>
            <% else %>
            <span class='text-secondary'>販売停止</span>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center" style="margin-top: 50px;">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<%= render partial: 'admin/items/form', locals: { title: '新規商品登録', url: admin_items_path, method: :post, item: @item, genres: @genres, submit_button_text: '新規登録' } %>

app/views/admin/items/show.html.erb
<div class='container' style="margin-top: 100px; margin-bottom: 100px;">
  <div class='row justify-content-center'>
    <div class="col-sm-12 col-md-10 col-lg-8 px-5 px-sm-0 mx-auto align-self-center text-start">
      <h3 class="text-center">商品詳細</h3>

      <div class="row">
        <!-- 商品の画像 -->
        <div class="col-md-6">
          <table class="table" style="border: none;">
            <tr>
              <td rowspan="5" style="border: none;" class="text-start">
                <div class="text-center mb-3">
                  <%= image_tag @item.image, size: "400x400", class: "img-fluid" %>
                </div>
              </td>
            </tr>
          </table>
        </div>
        <!-- 商品詳細 -->
        <div class="col-md-6">
          <table class="table" style="border: none;">
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">商品名</th>
              <td style="border: none;"><%= @item.name %></td>
            </tr>
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">商品説明</th>
              <td style="border: none; white-space: normal;"><%= @item.introduction %></td>
            </tr>
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">税込価格:</th>
              <td style="border: none; white-space: normal;">￥<%= number_with_delimiter((@item.price * 1.1).round, delimiter: ',') %> (税込)</td>
            </tr>
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">税抜価格:</th>
              <td style="border: none; white-space: normal;">￥<%= number_with_delimiter((@item.price).ceil.to_i, delimiter: ',') %> (税抜)</td>
            </tr>
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">ジャンル</th>
              <td style="border: none; white-space: normal;"><%= @item.genre.name %></td>
            </tr>
            <tr>
              <th class="text-end" style="border: none; white-space: nowrap;">販売ステータス</th>
              <td style="border: none; white-space: normal;">
                <% if @item.is_active %>
                  <span class='text-success'>販売中</span>
                <% else %>
                  <span class='text-secondary'>販売停止</span>
                <% end %>
              </td>
            </tr>
          </table>

          <div class="text-center">
            <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>