config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  get '/about', to: 'public/homes#about', as: 'about'
  # 退会処理
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe', as: 'public_customers_unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  get '/admin', to: 'admin/homes#top', as: 'admin_root'
  get 'customers/my_page', to: 'public/customers#show', as: 'public_customers'
  get 'customers/information/edit', to: 'public/customers#edit', as: 'public_customers_information_edit'

  get 'addresses', to: 'public/addresses#index', as: 'addresses'
  get 'addresses/:id/edit', to: 'public/addresses#edit', as: 'addresses_edit'
  patch 'public/addresses/:id', to: 'public/addresses#update'


  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  post '/customers/sign_in', to: 'public/sessions#create'

  namespace :public, path: '' do
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create] do
        post 'confirm', on: :collection
        get 'thanks', on: :collection
    end
    resources :items, except: [:destroy]
    resources :cart_items, only: [ :update, :destroy, :create, :show] do
      delete :destroy_all, on: :collection
    end
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
    # 修正した部分
    delete 'cart_items', to: 'cart_items#destroy_all'
    get 'cart_items', to: 'cart_items#index'  # カートアイテムを表示するためのルートを追加
  end
  # Move public/cart_items route definition outside of public namespace

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :homes, only: [:top]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  after_save :check_active_status
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  #全て空でないこと
   validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :telephone_number, :postal_code, :address, presence: true

  # is_deletedがfalseならtrueを返すようにしている(退会処理)
  def active_for_authentication?
    super && !is_deleted
  end

  # フルネームを返すメソッド
  def name
    "#{last_name} #{first_name}"
  end

  def full_name
    "#{last_name} #{first_name}"
  end

  private

  def check_active_status
   if saved_change_to_is_active? && !is_active
    # 顧客が退会処理を行った場合の処理
    self.update(is_active: false) # 退会ステータスを更新
   end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]) #ページネーション
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "顧客情報が正常に更新されました"
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address, :email, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--管理者側の会員情報編集ページ-->
<div class="container">
  <div class="row">
    <div class="mx-auto">

      <h2 class="mt-5">会員情報編集</h2>
      
      <%= form_with(model: @customer, url: admin_customer_path(@customer), local: true) do |form| %>
        <%= render "public/shared/error_messages", resource: @customer %>
        
        <table class="form-group d-flex align-items-center mt-4">
          <thead>
            <tr>
              <th></th>
            </tr>
          </thead>
          
          <tbody>
            <tr>
              <th class="nowrap col-md-4">会員ID</th>
              <td><%= @customer.id %></td>
            </tr>
            
            <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
            
             <tr>
               <th class="nowrap col-md-4">氏名</th>
               <td>
                 <div class="row g-3">
                   <div class="col-md-6"> 
                     <%= form.text_field :last_name, class: 'form-control' %>
                   </div>
                   <div class="col-md-6"> 
                     <%= form.text_field :first_name, class: 'form-control'%>
                   </div>
                </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
             
             <tr>
               <th class="nowrap col-md-4">フリガナ</th>
               <td>
                 <div class="row g-3">
                   <div class="col">
                     <%= form.text_field :last_name_kana, class: 'form-control' %>
                     </div>
                     <div class="col">
                       <%= form.text_field :first_name_kana, class: 'form-control' %>
                     </div>
                 </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
             
             <tr>
               <th class="nowrap col-md-4">郵便番号</th>
               <td>
                 <div class="row g-3">
                   <div class="col">
                     <%= form.text_field :postal_code, class: 'form-control' %>
                   </div>
                 </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
             
             <tr>
               <th class="nowrap col-md-4">住所</th>
               <td>
                 <div class="row g-3">
                   <div class="col">
                     <%= form.text_field :address, class: 'form-control' %>
                   </div>
                 </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
             
             <tr>
               <th class="nowrap col-md-4">電話番号</th>
               <td>
                 <div class="row g-3">
                   <div class="col">
                     <%= form.text_field :telephone_number, class: 'form-control' %>
                   </div>
                 </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
            </tr>
             
             <tr>
               <th class="nowrap col-md-4">メールアドレス</th>
               <td>
                 <div class="row g-3">
                   <div class="col">
                     <%= form.text_field :email, class: 'form-control' %>
                   </div>
                 </div>
               </td>
             </tr>
             
             <tr>
              <td colspan="2"></td> <!-- colspan="2" は、2列に合わせるために追加 -->
             </tr>

             <tr>
               <th class="nowrap col-md-4">会員ステータス</td>
                <td>
                  <div class="row g-3">
                   <div class="col">
                     <%= form.radio_button :is_active, true, id: "customer_is_active_true" %>
                     <%= form.label :is_active, "有効", value: true, for: "customer_is_active_true" %>
        
                     <%= form.radio_button :is_active, false, id: "customer_is_active_false" %>
                     <%= form.label :is_active, "退会", value: false, for: "customer_is_active_false" %>
                </td>
             </tr>

             <tr>
               <td></td>
                <td>
                 <input type="submit" name="commit" value="変更を保存" class="btn btn-success" data-disable-with="Update Book">
                </td>
             </tr>


      
      
          </tbody>
      </table>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<!--管理者側の会員一覧ページ-->
<div class="col-sm-9 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto align-self-center text-start" style="margin-top: 50px; margin-bottom: 50px;">
<div class="container">
  <div class="row">
    <h3>会員一覧</h3>
    <table class= "table table-hover table-inverse">

      <thead>
        <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to "#{customer.last_name} #{customer.first_name}",admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td>
          <% if customer.is_active %>
          <span class='text-success'>有効</span>
          <% else %>
          <span class='text-secondary'>退会</span>
      　   <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
      </table>
      <div class="d-flex justify-content-center" style="margin-top: 50px;">
      <%= paginate @customers %>
      </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!--管理者側の会員詳細ページ-->
  <!--<div class="row">-->
  <div class="col-sm-9 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto align-self-center text-start" style="margin-top: 50px; margin-bottom: 50px;">
    <div class="container">
      <div class="row">
        <div class="col">

          <h3 class="text-left md-4"><strong><%= @customer.last_name %> <%= @customer.first_name %></strong> さんの会員詳細</h3>
          
          <table class="table table-borderless">
            
            
            <tr>
              <th class="nowrap" style="font-size: 18px;">会員ID</th>
              <td style="font-size: 18px;"><%= @customer.id %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">氏名</th>
              <td style="font-size: 18px;"><%= "#{@customer.last_name} #{@customer.first_name}" %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">フリガナ</th>
              <td style="font-size: 18px;"><%= "#{@customer.last_name_kana} #{@customer.first_name_kana}" %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">郵便番号</th>
              <td style="font-size: 18px;"><%= @customer.postal_code %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">住所</th>
              <td style="font-size: 18px;"><%= @customer.address %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">電話番号</th>
              <td style="font-size: 18px;"><%= @customer.telephone_number %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">メールアドレス</th>
              <td style="font-size: 18px;"><%= @customer.email %></td>
            </tr>

            <tr>
              <th class="nowrap" style="font-size: 18px;">会員ステータス</th>
              <td style="font-size: 18px;">
                <% if @customer.is_active %>
                <span class='text-success'>有効</span>
                <% else %>
                <span class='text-secondary'>退会</span>
                <% end %>
              </td>
            </tr>

            <tr>
              <th></th>
              <td><%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %></td>
              <td><%= link_to '注文履歴一覧を見る', admin_orders_path(@customer.id), class: "btn btn-primary" %></td>
            </tr>
            
          </table>