config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  get '/about', to: 'public/homes#about', as: 'about'
  # 退会処理
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe', as: 'public_customers_unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  get '/admin', to: 'admin/homes#top', as: 'admin_root'
  get 'customers/my_page', to: 'public/customers#show', as: 'public_customers'
  get 'customers/information/edit', to: 'public/customers#edit', as: 'public_customers_information_edit'

  get 'addresses', to: 'public/addresses#index', as: 'addresses'
  get 'addresses/:id/edit', to: 'public/addresses#edit', as: 'addresses_edit'
  patch 'public/addresses/:id', to: 'public/addresses#update'


  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  post '/customers/sign_in', to: 'public/sessions#create'

  namespace :public, path: '' do
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create] do
        post 'confirm', on: :collection
        get 'thanks', on: :collection
    end
    resources :items, except: [:destroy]
    resources :cart_items, only: [ :update, :destroy, :create, :show] do
      delete :destroy_all, on: :collection
    end
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
    # 修正した部分
    delete 'cart_items', to: 'cart_items#destroy_all'
    get 'cart_items', to: 'cart_items#index'  # カートアイテムを表示するためのルートを追加
  end
  # Move public/cart_items route definition outside of public namespace

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :homes, only: [:top]
  end
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_details
  validates :name, presence: true
  validates :postal_code , presence: true
  validates :address, presence: true
 enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
#  enum導入
 enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10).order('created_at DESC')
    @order_details = OrderDetail.where(order_id: @orders.pluck(:id))
  end


  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

def update
  @order = Order.find(params[:id])
  @order.update(order_params)
  @order_details = @order.order_details

  if @order.status == "入金確認"
    @order_details.each do |order_detail|
      order_detail.update(making_status: "製作待ち")
    end
  end
  @order.save # 自動更新のために変更内容を保存する
  render :show
end


    private

  def order_params
   params.require(:order).permit(:status, order_details_attributes: [:making_status])
  end
  
  def is_all_order_details_making_completed(order)
    order.order_details.all? { |order_detail| order_detail.making_status == 'making_completed' }
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="col-sm-9 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto align-self-center text-start" style="margin-top: 50px; margin-bottom: 50px;">
  <h2>注文履歴一覧</h2>
   <div class="d-flex justify-content-around">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
       <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M'), admin_order_path(order) %></td>
            <td><%= order.name %></td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.status %></td>
          </tr>
        <% end %>
      </tbody>

  </table>
 </div>
</div>

app/views/admin/orders/show.html.erb
<div class="col-sm-9 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto align-self-center text-start" style="margin-top: 50px; margin-bottom: 50px;">
<h3>注文履歴詳細</h3>
<div class="row">
  <div class="col-xs-6">

      <div>
        <p>
          <strong class="col-xs-2">購入者</strong>
          <%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @order.customer.last_name %><%= @order.customer.first_name %>
          <% end %>
        </p>
      </div>
      <br>
      <div>
          <p>
          <strong class="col-xs-2">配送先</strong>
          <%= (@order.customer.postal_code).to_s.insert(3, "-") %>
          <%= @order.customer.address %>
          </p>
      </div>
      <br>
      <div>
          <p>
            <strong class="col-xs-2">支払い方法</strong>
            <%= t("enums.order.payment_method.#{@order.payment_method}") %>
          </p>
      </div>
      <br>
      <div>
          <p>
            <strong class="col-xs-4">注文ステータス</strong>
            <%= form_with model:@order, url: admin_order_path, local: true do |f| %>
              <%= f.select :status, ["入金待ち", "入金確認","製作中","発送準備中","発送済み"] %>
              <%= f.submit "更新", class: 'btn btn-primary' %>
            <% end %>
          </p>
      </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-8">
    <table class='order-show-table table'>
      <thead>
        <tr>
          <th class="active">商品名</th>
          <th class="active">単価（税込）</th>
          <th class="active">数量</th>
          <th class="active">小計</th>
          <th class="active">製作ステータス</th>
        <tr>
      </thead>
<% @order_details.each do |order_detail| %>
  <tbody>
    <tr>
      <td class="col-xs-4"><%= order_detail.item.name %></td>
      <td class="col-xs-2">¥<%= (order_detail.price * 1.1).floor.to_s(:delimited) %></td>
      <td><%= order_detail.amount %></td>
      <td class="col-xs-2">¥<%= ((order_detail.price * order_detail.amount * 1.1).floor).to_s(:delimited) %></td>
      <td>
        <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
          <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |status| [status.humanize, status] }, selected: order_detail.making_status %>
          <%= f.submit "更新", class: 'btn btn-primary' %>
        <% end %>
      </td>
    </tr>
  </tbody>
<% end %>
    </table>
  </div>
  <div class="col-xs-4">
    <div>
      <p>
        <strong class="col-xs-3">商品合計</strong>
         ¥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited)%>
      </p>
    </div>
    <br>

    <div>
      <p>
        <strong class="col-xs-2">送料</strong>
        ¥<%= @order.shipping_cost %>
      </p>
    </div>
    <br>

    <div>
      <p>
        <strong class="col-xs-4">請求金額合計</strong>
        ¥<%= @order.total_payment.to_s(:delimited) %>
      </p>
    </div>
    <br>
  </div>
</div>
</div>