config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
  get '/about', to: 'public/homes#about', as: 'about'
  # 退会処理
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe', as: 'public_customers_unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  get '/admin', to: 'admin/homes#top', as: 'admin_root'
  get 'customers/my_page', to: 'public/customers#show', as: 'public_customers'
  get 'customers/information/edit', to: 'public/customers#edit', as: 'public_customers_information_edit'

  get 'addresses', to: 'public/addresses#index', as: 'addresses'
  get 'addresses/:id/edit', to: 'public/addresses#edit', as: 'addresses_edit'
  patch 'public/addresses/:id', to: 'public/addresses#update'


  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  post '/customers/sign_in', to: 'public/sessions#create'

  namespace :public, path: '' do
    resources :addresses, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create] do
        post 'confirm', on: :collection
        get 'thanks', on: :collection
    end
    resources :items, except: [:destroy]
    resources :cart_items, only: [ :update, :destroy, :create, :show] do
      delete :destroy_all, on: :collection
    end
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations, only: [:new, :create]
    # 修正した部分
    delete 'cart_items', to: 'cart_items#destroy_all'
    get 'cart_items', to: 'cart_items#index'  # カートアイテムを表示するためのルートを追加
  end
  # Move public/cart_items route definition outside of public namespace

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:index, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :show]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :homes, only: [:top]
  end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
  #全て空でないこと
   validates :postal_code, :address, :name, presence: true
 
   def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
   end
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  belongs_to :order, optional: true


  def subtotal
    item.price_including_tax * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  after_save :check_active_status
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :cart_items
  has_many :orders

  #全て空でないこと
   validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :telephone_number, :postal_code, :address, presence: true

  # is_deletedがfalseならtrueを返すようにしている(退会処理)
  def active_for_authentication?
    super && !is_deleted
  end

  # フルネームを返すメソッド
  def name
    "#{last_name} #{first_name}"
  end

  def full_name
    "#{last_name} #{first_name}"
  end

  private

  def check_active_status
   if saved_change_to_is_active? && !is_active
    # 顧客が退会処理を行った場合の処理
    self.update(is_active: false) # 退会ステータスを更新
   end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, optional: true
  has_many :cart_items

  validates :genre, presence: { message: "を選択してください" }
  validates :price, presence: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :image, presence: true
  validates :introduction, presence: true, length: { maximum: 70 }

  scope :search, ->(query) {
    where("name LIKE ?", "%#{query}%") if query.present?
  }

end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :cart_items
   has_many :order_details
  validates :name, presence: true
  validates :postal_code , presence: true
  validates :address, presence: true
 enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
#  enum導入
 enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

#製作ステータス
enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.page(params[:page])
    @genre = Genre.new
  end

  def show
    redirect_to edit_admin_genre_path(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      flash[:notice] = "ジャンルを追加しました。"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "ジャンルの追加に失敗しました。"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end


  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルを変更しました。"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "ジャンルの変更に失敗しました。"
      render :edit
    end
  end


private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
 def top
  end

  def about
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!
  def index
   @items = Item.search(params[:q]).page(params[:page])
  end

  def new
   @item = Item.new
   @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
     flash[:notice] = "商品を追加しました。"
      redirect_to admin_item_path(@item.id)
    else
     flash.now[:alert] = "商品の追加に失敗しました。"
      render new_admin_item_path
    end
  end

  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
   @genres = Genre.all
  end

 def update
   @item = Item.find(params[:id])
   @genres = Genre.all
   if @item.update(item_params)
    flash[:notice] = "状態を変更しました。"
     redirect_to admin_item_path(@item.id)
   else
     flash.now[:alert] = "状態の変更に失敗しました。"
     render :edit
   end
 end

    private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase) %>
    </h2>
    <ul>
  <% resource.errors.full_messages.each do |message| %>
    <li><%= I18n.t(message) %></li>
  <% end %>
</ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color: #a0522d; color: white;">
  <div class='container'>
    <div class='row'>
      <div class='col-6'>
          <p></p>
        <div>
          <i class="fa-brands fa-twitter"></i>
          <i class="fa-brands fa-instagram"></i>
          <i class="fa-brands fa-tiktok"></i>
        </div>
      </div>
      <div class='col-6 text-right'>
          <p></p>
        <div>
          <p>Team <%= content_tag(:i, "", class: "fa-solid fa-cake-candles") %> Jump</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- 上部 -->
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #a0522d;">
    <div class="container">
      <!-- 上部左端に配置 -->
     <div class="d-lg-flex d-none align-items-center col-lg-4 mr-auto">
      <!-- Nagano Cake テキスト -->
      <% if customer_signed_in? %>
        <%= link_to root_path, class: "navbar-brand", style: "margin-right: auto; margin-left: 0;" do %>
          <%= image_tag("nagano_cake1.jpg", alt: "Nagano Cake", size: "100x100") %>
        <% end %>
      <% elsif admin_signed_in? %>
        <%= link_to admin_items_path, class: "navbar-brand", style: "margin-right: auto; margin-left: 0;" do %>
          <%= image_tag("nagano_cake1.jpg", alt: "Nagano Cake", size: "100x100") %>
        <% end %>
      <% else %>
        <%= link_to root_path, class: "navbar-brand", style: "margin-right: auto; margin-left: 0;" do %>
          <%= image_tag("nagano_cake1.jpg", alt: "Nagano Cake", size: "100x100") %>
        <% end %>
      <% end %>
    </div>


      <!-- 上部中央に配置 -->
      <div class=" d-lg-flex d-none align-items-center col-lg-8">
        <!-- 検索ボックス -->
      <form class="form-inline my-2 my-lg-0 ml-auto" action="<%= admin_signed_in? ? admin_items_path : public_items_path %>" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="検索" name="q">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">🔍</button>
      </form>
      </div>
    </div>
  </nav>
  <!-- 下部 -->
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #a0522d;">
    <div class="container">
      <!-- 下部左に配置 -->
      <div class="col-lg-6">
        <!-- ログインしている場合の下部メッセージ -->
        <% if customer_signed_in? %>
          <span class="text-light mr-12"><%= current_customer.last_name %> さまようこそ</span>
        <% elsif admin_signed_in? %>
          <span class="text-light mr-12">Administrator</span>
        <% end %>
      </div>
      <!--下部右に配置-->
      <div class="col-lg-6">
        <!-- ハンバーガー・・・なくてもよさそう -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <!-- ログインしていない場合 -->
            <% unless admin_signed_in? || customer_signed_in? %>
              <li class="header_text">
                <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
                  SignUp
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to new_customer_session_path,class: 'nav-link text-light' do %>
                  Log in
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to public_items_path,class: 'nav-link text-light' do %>
                Items
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to about_path,class: 'nav-link text-light' do %>
                About
                <% end %>
              </li>
            <% end %>
            <!-- 管理者がログインしている場合 -->
            <% if admin_signed_in? %>
              <li class="header_text">
                <%= link_to admin_items_path,class: 'nav-link text-light' do %>
                  Items
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to admin_customers_path,class: 'nav-link text-light' do %>
                Customers
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to admin_orders_path,class: 'nav-link text-light' do %>
                  Order history
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to admin_genres_path,class: 'nav-link text-light' do %>
                Genres
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
                Log out
                <% end %>
              </li>
            <% end %>
            <!-- 顧客がログインしている場合 -->
            <% if customer_signed_in? %>
              <li class="header_text">
                <%= link_to public_customers_path,class: 'nav-link text-light' do %>
                MyPage
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to public_items_path,class: 'nav-link text-light' do %>
                Items
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to public_cart_items_path,class: 'nav-link text-light' do %>
                Cart
                <% end %>
              </li>
              <li class="header_text">
                <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
                Log out
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!--聖前-->
    <script src="https://kit.fontawesome.com/97dbd80b90.js" crossorigin="anonymous"></script>
    <!--柴田-->
    <script src="https://kit.fontawesome.com/8b6488317f.js" crossorigin="anonymous"></script>
    <!--岩永-->
    <script src="https://kit.fontawesome.com/e5fd4ead5a.js" crossorigin="anonymous"></script>
    <!--森-->
    <script src="https://kit.fontawesome.com/99f9963ced.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'custom_styles', media: 'all' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <main style="background-color: #FAEBD7;">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>